import "./globals.css";
import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import { NavBar } from "@/views/includes/NavBar";


const web_font = IBM_Plex_Mono({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Blakprint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={web_font.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
